url:
  url version 2
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.222.19:3306/cloud_action?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xdjr1230-KFCG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml